version: "3"
services:
  app:
    container_name: app_container
    restart: always
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION=mongodb://mongodb:27017/Covid19Data
    depends_on:
      - mongodb
    links: 
      - mongodb
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  # seeds the mongo DB
  # restarts b/c no way to make it wait until mongoDB is fully started before importing so import
  # fails first couple of times typically
  mongo-seed-1:
    build: ./mongo-seed-1
    depends_on: 
      - mongodb
    restart: on-failure
    links: 
      - mongodb
  mongo-seed-2:
    build: ./mongo-seed-2
    depends_on: 
      - mongodb
    restart: on-failure
    links: 
      - mongodb
    